version: "3"
services:
  common:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: collabtexteditor/common
  go-server-common:
    build:
      context: ./
      dockerfile: ./backend/docker/common/Dockerfile
    image: collabtexteditor/go-server-common
  envoy:
    build:
      context: ./
      dockerfile: ./envoy/Dockerfile
    image: collabtexteditor/envoy
    ports:
      - "8080:8080"
  frontend-client:
    build:
      context: ./frontend
    depends_on:
      - common
    image: collabtexteditor/frontend-client
    ports:
      - "8081:8081"