version: "3"
services:
  common:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: collabtexteditor/common
  go-server:
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
    depends_on:
      - common
    image: collabtexteditor/go-server
    ports:
      - "9090:9090"
  envoy:
    build:
      context: ./
      dockerfile: ./envoy/Dockerfile
    image: collabtexteditor/envoy
    ports:
      - "8080:8080"
  frontend-client:
    build:
      context: ./frontend
    depends_on:
      - common
    image: collabtexteditor/frontend-client
    ports:
      - "8081:8081"