version: "3"
services:
  chromium:
    build:
      context: ./frontend/docker/chromium
      dockerfile: ./Dockerfile
    image: collabtexteditor/chromium
  common:
    build:
      context: ./
      dockerfile: ./frontend/docker/common/Dockerfile
    depends_on:
      - chromium
    image: collabtexteditor/common
  go-server-common:
    build:
      context: ./
      dockerfile: ./backend/docker/common/Dockerfile
    image: collabtexteditor/go-server-common
  go-server:
    image: collabtexteditor/go-server
  envoy:
    build:
      context: ./
      dockerfile: ./envoy/Dockerfile
    image: collabtexteditor/envoy
    ports:
      - "8080:8080"
  frontend-client:
    build:
      context: ./frontend
    depends_on:
      - common
    image: collabtexteditor/frontend-client
    ports:
      - "8081:8081"